'use client';

import React, { useState } from 'react';
import Modal from '@/components/ui/Modal';
import { ArrowLeft, ArrowRight, Check, ChevronDown, Copy, Plus } from 'lucide-react';

type Provider = 'tata' | 'exotel' | 'knowlarity' | 'mcube';
type Direction = 'Inbound' | 'Outbound';
type User = { name: string; forward: string; email: string; extension: string; callingAgent: boolean; blocked: boolean; disabled: boolean };

const PROVIDER_FIELDS: Record<Provider, string[][]> = {
	tata: [['userId', 'UserId'], ['agentId', 'AgentId'], ['campaignName', 'CampaignName'], ['userName', 'UserName'], ['isActive', 'IsActive'], ['setting', 'Setting'], ['mapping', 'Mapping'], ['httpClientHeaders', 'HttpClientHeaders'], ['httpMethod', 'HttpMethod'], ['countryCode', 'CountryCode'], ['orderid', 'orderid'], ['retrydelta', 'retrydelta'], ['callretries', 'callretries'], ['baseurl', 'Baseurl']],
	exotel: [['apiKey', 'API Key'], ['apiToken', 'API Token'], ['subdomain', 'Subdomain'], ['virtualNumber', 'Virtual Number'], ['webhookUrl', 'Webhook URL']],
	knowlarity: [['apiKey', 'API Key'], ['sid', 'SID'], ['authToken', 'Auth Token'], ['virtualNumber', 'Virtual Number'], ['webhookUrl', 'Webhook URL']],
	mcube: [['username', 'Username'], ['apiKey', 'API Key'], ['virtualNumber', 'Virtual Number'], ['webhookUrl', 'Webhook URL']],
};

const PROVIDER_NAMES: Record<Provider, string> = { tata: 'TATA IVR', exotel: 'Exotel IVR', knowlarity: 'Knowlarity IVR', mcube: 'MCube IVR' };
const input = 'w-full h-9 px-3 text-[12px] bg-card border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary';
const label = 'block text-[11px] font-semibold text-muted-foreground mb-1.5';

function Toggle({ value, onChange, labels = ['NO', 'YES'] }: { value: boolean; onChange: (value: boolean) => void; labels?: [string, string] }) {
	return <div className="inline-flex rounded-lg border border-border bg-muted/40 p-0.5"><button type="button" onClick={() => onChange(false)} className={`h-7 px-3 text-[11px] font-semibold rounded-md ${!value ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground'}`}>{labels[0]}</button><button type="button" onClick={() => onChange(true)} className={`h-7 px-3 text-[11px] font-semibold rounded-md ${value ? 'bg-primary text-white shadow-sm' : 'text-muted-foreground'}`}>{labels[1]}</button></div>;
}

function TextField({ name, value, onChange, type = 'text', required = false }: { name: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) {
	return <label className="block"><span className={label}>{name}{required && <span className="text-danger"> *</span>}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} className={input} /></label>;
}

export default function TataIntegrationPopup({ open, onClose, provider = 'tata' }: { open: boolean; onClose: () => void; provider?: Provider }) {
	const [step, setStep] = useState(0);
	const [direction, setDirection] = useState<Direction>('Inbound');
	const [extension, setExtension] = useState(false);
	const [configSaved, setConfigSaved] = useState(false);
	const [agentExtension, setAgentExtension] = useState(false);
	const [callingAgent, setCallingAgent] = useState(false);
	const [sameAsUser, setSameAsUser] = useState(false);
	const [blocked, setBlocked] = useState(false);
	const [config, setConfig] = useState<Record<string, string>>({ empId: '081818881818' });
	const [user, setUser] = useState({ name: '', mobile: '', country: '+91', designation: '', email: '', team: '', department: '', forward: '', callerIds: '' });
	const [route, setRoute] = useState('Both');
	const [users, setUsers] = useState<User[]>([]);
	const [menu, setMenu] = useState<number | null>(null);
	const [userTab, setUserTab] = useState<'general' | 'settings'>('general');
	const [confirmAction, setConfirmAction] = useState<{ action: 'Delete' | 'Block' | 'Disable'; index: number } | null>(null);
	const updateConfig = (key: string, value: string) => setConfig((current) => ({ ...current, [key]: value }));
	const updateUser = (key: keyof typeof user, value: string) => setUser((current) => ({ ...current, [key]: value }));
	const clearUser = () => { setUser({ name: '', mobile: '', country: '+91', designation: '', email: '', team: '', department: '', forward: '', callerIds: '' }); setSameAsUser(false); setBlocked(false); setCallingAgent(false); setAgentExtension(false); setRoute('Both'); setUserTab('general'); };
	const close = () => { setStep(0); onClose(); };
	const submitUser = () => { if (!user.name.trim() || !user.email.trim()) return; setUsers((current) => [...current, { name: user.name, forward: sameAsUser ? `${user.country} ${user.mobile}` : user.forward, email: user.email, extension: callingAgent && agentExtension ? (config.empId || '081818881818') : 'Not created', callingAgent, blocked, disabled: false }]); clearUser(); setStep(3); };
	const applyConfirmedAction = () => {
		if (!confirmAction) return;
		setUsers((current) => current.flatMap((record, index) => {
			if (index !== confirmAction.index) return [record];
			if (confirmAction.action === 'Delete') return [];
			return [{ ...record, blocked: confirmAction.action === 'Block' ? true : record.blocked, disabled: confirmAction.action === 'Disable' ? true : record.disabled }];
		}));
		setConfirmAction(null);
		setMenu(null);
	};
	const steps = ['Setup', 'General Details', 'User Settings', 'Web Login'];
	const providerName = PROVIDER_NAMES[provider];

	return <Modal open={open} onClose={close} title={`${providerName} Integration`} subtitle={steps[step]} size="2xl" footer={<div className="flex items-center justify-between"><button type="button" onClick={() => step === 0 ? close() : setStep((current) => current - 1)} className="flex items-center gap-1.5 h-8 px-3 text-[11px] font-medium border border-border rounded-lg hover:bg-muted">{step === 0 ? 'Cancel' : <><ArrowLeft size={13} />Previous</>}</button><div className="flex items-center gap-2">{step > 0 && <button type="button" onClick={clearUser} className="h-8 px-3 text-[11px] font-medium text-muted-foreground hover:text-foreground">Clear</button>}{step === 0 && <><button type="button" onClick={() => setConfigSaved(true)} className="h-8 px-4 text-[11px] font-semibold border border-border rounded-lg hover:bg-muted">{configSaved ? 'Saved' : 'Save'}</button><button type="button" onClick={() => { setConfigSaved(true); setStep(1); }} className="flex items-center gap-1.5 h-8 px-4 text-[11px] font-semibold bg-primary text-white rounded-lg">Next <ArrowRight size={13} /></button></>}{step === 1 && <button type="button" onClick={() => setStep(2)} disabled={!user.name.trim() || !user.email.trim()} className="flex items-center gap-1.5 h-8 px-4 text-[11px] font-semibold bg-primary text-white rounded-lg disabled:opacity-50">Next <ArrowRight size={13} /></button>}{step === 2 && <button type="button" onClick={submitUser} disabled={!user.name.trim() || !user.email.trim()} className="h-8 px-4 text-[11px] font-semibold bg-primary text-white rounded-lg disabled:opacity-50">Submit</button>}{step === 3 && <button type="button" onClick={() => setStep(1)} className="flex items-center gap-1.5 h-8 px-4 text-[11px] font-semibold bg-primary text-white rounded-lg"><Plus size={13} />Add User</button>}</div></div>}>
		<div className="flex items-center gap-2 mb-5">{steps.map((current, index) => <React.Fragment key={current}><div className={`flex items-center gap-2 text-[10px] font-semibold ${index === step ? 'text-primary' : index < step ? 'text-foreground' : 'text-muted-foreground'}`}><span className={`flex items-center justify-center w-6 h-6 rounded-full border ${index < step ? 'bg-primary border-primary text-white' : index === step ? 'border-primary text-primary' : 'border-border'}`}>{index < step ? <Check size={12} /> : index + 1}</span><span className="hidden sm:inline">{current}</span></div>{index < steps.length - 1 && <div className={`h-px flex-1 ${index < step ? 'bg-primary' : 'bg-border'}`} />}</React.Fragment>)}</div>
		{step === 0 && <div className="space-y-5"><div className="flex items-center justify-between p-4 rounded-xl border border-border bg-muted/20"><div><p className="text-[12px] font-semibold">Call direction</p><p className="text-[11px] text-muted-foreground mt-0.5">Only configuration needed for the selected direction is shown.</p></div><div className="inline-flex rounded-lg border border-border bg-card p-0.5"><button type="button" onClick={() => setDirection('Inbound')} className={`h-8 px-4 text-[11px] font-semibold rounded-md ${direction === 'Inbound' ? 'bg-primary text-white' : 'text-muted-foreground'}`}>Inbound</button><button type="button" onClick={() => setDirection('Outbound')} className={`h-8 px-4 text-[11px] font-semibold rounded-md ${direction === 'Outbound' ? 'bg-primary text-white' : 'text-muted-foreground'}`}>Outbound</button></div></div>{direction === 'Outbound' && <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{PROVIDER_FIELDS[provider].map(([key, name]) => <TextField key={key} name={name} value={config[key] || ''} onChange={(value) => updateConfig(key, value)} />)}<div className="sm:col-span-2 flex items-center justify-between p-3 rounded-lg border border-border"><div><p className="text-[11px] font-semibold">IS Extension</p><p className="text-[10px] text-muted-foreground">Create an employee extension for outbound calls.</p></div><Toggle value={extension} onChange={setExtension} labels={['NO', 'YES']} /></div>{extension && <div className="sm:col-span-2 max-w-sm"><TextField name="EmpId" value={config.empId || '081818881818'} onChange={(value) => updateConfig('empId', value)} required /></div>}</div>}</div>}
		{step === 1 && <div className="space-y-4"><div className="flex border-b border-border"><button type="button" onClick={() => setUserTab('general')} className={`px-4 py-2.5 text-[11px] font-semibold border-b-2 ${userTab === 'general' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground'}`}>General Details</button><button type="button" disabled className="px-4 py-2.5 text-[11px] font-semibold border-b-2 border-transparent text-muted-foreground/50 cursor-not-allowed">User Settings</button></div><section className="rounded-xl border border-border p-4"><h3 className="text-[13px] font-semibold">General Details</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4"><TextField name="Name" value={user.name} onChange={(value) => updateUser('name', value)} required /><div><span className={label}>Mobile Number</span><div className="flex gap-2"><input value={user.country} onChange={(event) => updateUser('country', event.target.value)} className={`${input} w-20`} /><input value={user.mobile} onChange={(event) => updateUser('mobile', event.target.value)} className={`${input} flex-1`} /></div></div><TextField name="Designation" value={user.designation} onChange={(value) => updateUser('designation', value)} /><TextField name="Email Address" value={user.email} onChange={(value) => updateUser('email', value)} type="email" required /></div></section></div>}
		{step === 2 && <div className="space-y-4"><section className="rounded-xl border border-border p-4 space-y-4"><h3 className="text-[12px] font-semibold">1. Agent Assignment</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><TextField name="Assign agent to Team" value={user.team} onChange={(value) => updateUser('team', value)} /><TextField name="Assign agent to Department" value={user.department} onChange={(value) => updateUser('department', value)} /></div></section><section className="rounded-xl border border-border p-4 space-y-4"><h3 className="text-[12px] font-semibold">2. Call Settings</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><span className={label}>Call Forward Number</span><input value={user.forward} onChange={(event) => updateUser('forward', event.target.value)} disabled={sameAsUser} placeholder="With country code" className={`${input} disabled:bg-muted/40`} /><label className="flex items-center gap-1.5 mt-2 text-[10px] text-muted-foreground"><input type="checkbox" checked={sameAsUser} onChange={(event) => setSameAsUser(event.target.checked)} />Same as User Number</label></div><TextField name="Allowed Caller IDs" value={user.callerIds} onChange={(value) => updateUser('callerIds', value)} /><div className="sm:col-span-2 flex items-center justify-between p-3 rounded-lg bg-muted/20 border border-border"><span className="text-[11px] font-semibold">Block Agent</span><Toggle value={blocked} onChange={setBlocked} /></div></div></section><section className="rounded-xl border border-border p-4 space-y-4"><h3 className="text-[12px] font-semibold">3. Extension Settings</h3><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold">Calling Agent</p><p className="text-[10px] text-muted-foreground">Do you want to create an Agent Extension?</p></div><Toggle value={callingAgent} onChange={setCallingAgent} /></div>{callingAgent && <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 border-t border-border pt-4"><div><span className={label}>Create Agent Extension</span><Toggle value={agentExtension} onChange={setAgentExtension} labels={['OFF', 'ON']} /></div>{agentExtension && <label><span className={label}>Route Agent Through</span><select value={route} onChange={(event) => setRoute(event.target.value)} className={input}><option>Both</option><option>View Phone Number</option><option>View Extension</option></select></label>}</div>}</section></div>}
		{step === 3 && <div className="rounded-xl border border-border overflow-visible"><div className="grid grid-cols-[1.1fr_1fr_1.2fr_1fr_1fr_28px] gap-3 px-4 py-2.5 bg-muted/50 border-b border-border"><span className={label}>Name</span><span className={label}>Call Forward Number</span><span className={label}>Email</span><span className={label}>Agent Extension</span><span className={label}>Web Login Calling Agent</span><span /></div><div className="divide-y divide-border">{users.map((current, index) => <div key={`${current.email}-${index}`} className="grid grid-cols-[1.1fr_1fr_1.2fr_1fr_1fr_28px] gap-3 px-4 py-3 items-center"><span className="text-[11px] font-semibold truncate">{current.name}</span><span className="text-[11px] text-muted-foreground truncate">{current.forward || '-'}</span><span className="text-[11px] text-muted-foreground truncate">{current.email}</span><span className="text-[11px] text-muted-foreground truncate">{current.extension}</span><span className="text-[11px] text-muted-foreground">{current.callingAgent ? 'Enabled' : 'Disabled'}</span><div className="relative"><button type="button" onClick={() => setMenu(menu === index ? null : index)} className="p-1.5 rounded hover:bg-muted"><ChevronDown size={14} /></button>{menu === index && <div className="absolute right-0 top-8 z-10 w-36 rounded-lg border border-border bg-card shadow-lg p-1"><button className="w-full text-left px-2 py-1.5 text-[10px] hover:bg-muted">Edit User</button><button onClick={() => { setUsers((all) => all.filter((_, item) => item !== index)); setMenu(null); }} className="w-full text-left px-2 py-1.5 text-[10px] hover:bg-muted">Delete User</button><button className="w-full text-left px-2 py-1.5 text-[10px] hover:bg-muted">Block Agent</button><button className="w-full text-left px-2 py-1.5 text-[10px] hover:bg-muted">Disable Agent</button><button onClick={() => { setUsers((all) => [...all, { ...current, name: `${current.name} (Copy)`, email: `copy-${current.email}` }]); setMenu(null); }} className="flex items-center gap-1.5 w-full text-left px-2 py-1.5 text-[10px] hover:bg-muted"><Copy size={11} />Duplicate</button></div>}</div></div>)}{users.length === 0 && <p className="px-4 py-10 text-center text-[11px] text-muted-foreground">No users added yet.</p>}</div></div>}
	</Modal>;
}
